import { BaseRepository } from './BaseRepository';
import { DatabaseService } from './DatabaseService';
import { Agent, AgentQueryFilters } from '../models/Agent';
import { AgentId } from '../models/Types';
import { safeJsonParse } from '../utils/jsonUtils';
import { isValidUUID } from '../utils/uuidUtils';

/**
 * Repository for Agent entities with PostgreSQL persistence.
 *
 * Identity contract (see migration 016 and 018): the application identifies an
 * agent by its **slug id**, and `Agent.id` at every layer above this class is
 * that slug. The `agents.id` UUID is a deployment-local surrogate that exists
 * only to satisfy the primary key and two legacy FKs; it is generated by the
 * database, never chosen by the application, and never returned above this
 * class. Every read and write below resolves the slug to the surrogate
 * internally, so no caller needs to know a UUID exists.
 */
export class AgentRepository extends BaseRepository<Agent> {
  constructor(db: DatabaseService) {
    super(db, 'agents', 'druids_core');
  }

  /**
   * Convert Agent entity to database row format.
   *
   * Deliberately emits neither `id` nor `slug_id`:
   * - `id` is the DB-generated surrogate. Emitting it would either insert an
   *   invalid UUID (since `agent.id` is a slug) or rewrite the primary key.
   * - `slug_id` is immutable identity, set once by `create`. Leaving it out of
   *   the column set means `update` can never rewrite it, so renaming an agent
   *   cannot change what it *is*.
   */
  protected entityToRow(agent: Agent): Record<string, any> {
    // Only emit columns for fields the caller actually supplied.
    //
    // This is called with a Partial on the update path, and the previous version
    // read every field unconditionally — so an omitted field yielded `undefined`
    // and was written as NULL. Worse, the `|| []` / `|| {}` defaults turned an
    // omitted field into a *defined* empty value, which no undefined-filter can
    // catch: a partial update of one field silently reset mcpTools, metadata,
    // tags and the rest to empty.
    //
    // Mirrors RealmRepository.entityToRow, which was already written this way.
    // Nullish defaults are still applied when the field *is* present, so
    // behaviour for a full entity is unchanged. Omitted columns fall back to the
    // schema defaults on insert.
    //
    // Deliberately absent: `id` and `slug_id`. The surrogate is generated by the
    // database and slug_id is immutable identity, set once by create().
    const row: Record<string, any> = {};

    if (agent.name !== undefined) row['name'] = agent.name;
    if (agent.type !== undefined) row['type'] = agent.type;
    if (agent.status !== undefined) row['status'] = agent.status;
    if (agent.description !== undefined) row['description'] = agent.description;
    if (agent.capabilities !== undefined) row['capabilities'] = JSON.stringify(agent.capabilities);
    if (agent.specialization !== undefined) row['specialization'] = JSON.stringify(agent.specialization);
    if (agent.personality !== undefined) row['personality'] = JSON.stringify(agent.personality);
    if (agent.mcpTools !== undefined) row['mcp_tools'] = JSON.stringify(agent.mcpTools || []);
    if (agent.toolPermissions !== undefined) row['tool_permissions'] = JSON.stringify(agent.toolPermissions || {});
    if (agent.resourceAccess !== undefined) row['resource_access'] = agent.resourceAccess ? JSON.stringify(agent.resourceAccess) : null;
    if (agent.llmConfig !== undefined) row['llm_config'] = JSON.stringify(agent.llmConfig);
    if (agent.resourceLimits !== undefined) row['resource_limits'] = JSON.stringify(agent.resourceLimits);
    if (agent.bindings !== undefined) row['bindings'] = JSON.stringify(agent.bindings || []);
    if (agent.realmAccess !== undefined) row['realm_access'] = JSON.stringify(agent.realmAccess || {});
    if (agent.deployment !== undefined) row['deployment'] = JSON.stringify(agent.deployment || {});
    if (agent.tags !== undefined) row['tags'] = JSON.stringify(agent.tags || []);
    if (agent.metadata !== undefined) row['metadata'] = JSON.stringify(agent.metadata || {});
    if (agent.promptConfig !== undefined) row['prompt_config'] = agent.promptConfig ? JSON.stringify(agent.promptConfig) : null;
    if (agent.createdAt !== undefined) row['created_at'] = agent.createdAt;
    if (agent.updatedAt !== undefined) row['updated_at'] = agent.updatedAt;
    if (agent.lastModifiedBy !== undefined) row['last_modified_by'] = agent.lastModifiedBy || null;
    if (agent.version !== undefined) row['version'] = agent.version || 1;

    return row;
  }

  /**
   * Convert database row to Agent entity format
   */
  protected rowToEntity(row: Record<string, any>): Agent {
    return {
      // The slug is the application-facing identity. The surrogate UUID is only
      // a fallback for a row written outside the application before migration
      // 018 backfilled the column.
      id: row['slug_id'] ?? row['id'],
      name: row['name'],
      type: row['type'],
      status: row['status'],
      description: row['description'],
      capabilities: safeJsonParse(row['capabilities'], []),
      specialization: safeJsonParse(row['specialization'], {}),
      personality: safeJsonParse(row['personality'], {}),
      mcpTools: safeJsonParse(row['mcp_tools'], []),
      toolPermissions: safeJsonParse(row['tool_permissions'], {}),
      resourceAccess: row['resource_access'] ? safeJsonParse(row['resource_access'], undefined) : undefined,
      llmConfig: safeJsonParse(row['llm_config'], {}),
      resourceLimits: safeJsonParse(row['resource_limits'], {}),
      bindings: safeJsonParse(row['bindings'], []),
      realmAccess: safeJsonParse(row['realm_access'], {}),
      deployment: safeJsonParse(row['deployment'], {}),
      tags: safeJsonParse(row['tags'], []),
      metadata: safeJsonParse(row['metadata'], {}),
      promptConfig: row['prompt_config'] ? safeJsonParse(row['prompt_config'], undefined) : undefined,
      createdAt: row['created_at'],
      updatedAt: row['updated_at'],
      lastModifiedBy: row['last_modified_by'],
      version: row['version'] || 1
    };
  }

  /**
   * Resolve an application-level agent id to the database surrogate key.
   *
   * A UUID is passed through so the two legacy UUID FK paths still work. A slug
   * is looked up against the unique index. A miss returns null — this must never
   * invent an id, which is precisely the defect that produced duplicate agent
   * rows: the previous in-memory mapper minted a random UUID on a miss, the
   * subsequent update found nothing, and the caller fell through to an insert.
   */
  private async resolveDbId(idOrSlug: string): Promise<string | null> {
    if (isValidUUID(idOrSlug)) {
      return idOrSlug;
    }

    const query = `SELECT id FROM ${this.getFullTableName()} WHERE slug_id = $1`;
    const { rows } = await this.db.query(query, [idOrSlug]);
    return rows.length > 0 ? rows[0]['id'] : null;
  }

  /**
   * Create an agent, keyed on its slug id and idempotent on conflict.
   *
   * The surrogate UUID is left to the column default rather than supplied, and
   * `ON CONFLICT (slug_id)` makes a repeated create converge on one row instead
   * of inserting another. Callers that "update, and create if missing" are
   * therefore safe by construction.
   */
  override async create(entityData: Omit<Agent, 'id' | 'createdAt' | 'updatedAt'>): Promise<Agent> {
    const candidate = entityData as Agent;
    const slug = candidate.id;

    if (!slug || isValidUUID(slug)) {
      throw new Error(
        `AgentRepository.create requires a slug id, received ${slug ? 'a UUID' : 'nothing'}. ` +
        'Agents are identified by slug (see migration 018); the UUID is database-internal.'
      );
    }

    // Mirrors BaseRepository.create, which authoritatively stamps both
    // timestamps rather than trusting the caller's values.
    const now = new Date().toISOString();
    const entity = { ...candidate, createdAt: now, updatedAt: now } as Agent;

    const row: Record<string, any> = { ...this.entityToRow(entity), slug_id: slug };
    const columns = Object.keys(row);
    const placeholders = columns.map((_, index) => `$${index + 1}`);

    // created_at and slug_id are identity/provenance: preserve the original row's
    // values when converging on an existing agent.
    const assignments = columns
      .filter((col) => col !== 'slug_id' && col !== 'created_at')
      .map((col) => `${col} = EXCLUDED.${col}`)
      .join(', ');

    const query = `
      INSERT INTO ${this.getFullTableName()} (${columns.join(', ')})
      VALUES (${placeholders.join(', ')})
      ON CONFLICT (slug_id) DO UPDATE SET ${assignments}
      RETURNING *
    `;

    const { rows } = await this.db.query(query, columns.map((col) => row[col]));
    return this.rowToEntity(rows[0]);
  }

  override async findById(idOrSlug: string): Promise<Agent | null> {
    const dbId = await this.resolveDbId(idOrSlug);
    return dbId ? super.findById(dbId) : null;
  }

  override async update(idOrSlug: string, updates: Partial<Omit<Agent, 'id' | 'createdAt'>>): Promise<Agent | null> {
    const dbId = await this.resolveDbId(idOrSlug);
    return dbId ? super.update(dbId, updates) : null;
  }

  override async delete(idOrSlug: string): Promise<boolean> {
    const dbId = await this.resolveDbId(idOrSlug);
    return dbId ? super.delete(dbId) : false;
  }

  override async exists(idOrSlug: string): Promise<boolean> {
    const dbId = await this.resolveDbId(idOrSlug);
    return dbId ? super.exists(dbId) : false;
  }

  /**
   * Find agents with advanced filtering
   */
  async findWithFilters(filters: AgentQueryFilters): Promise<Agent[]> {
    let query = `SELECT * FROM ${this.getFullTableName()}`;
    const params: any[] = [];
    const conditions: string[] = [];

    // Type filtering
    if (filters.type) {
      const types = Array.isArray(filters.type) ? filters.type : [filters.type];
      conditions.push(`type = ANY($${params.length + 1})`);
      params.push(types);
    }

    // Status filtering
    if (filters.status) {
      const statuses = Array.isArray(filters.status) ? filters.status : [filters.status];
      conditions.push(`status = ANY($${params.length + 1})`);
      params.push(statuses);
    }

    // Domain filtering (search in specialization JSON)
    if (filters.domain) {
      conditions.push(`specialization->>'domain' = $${params.length + 1}`);
      params.push(filters.domain);
    }

    // Capabilities filtering (search in capabilities JSON array)
    if (filters.capabilities && filters.capabilities.length > 0) {
      conditions.push(`capabilities ?| $${params.length + 1}`);
      params.push(filters.capabilities);
    }

    // Tags filtering (search in tags JSON array)
    if (filters.tags && filters.tags.length > 0) {
      conditions.push(`tags ?| $${params.length + 1}`);
      params.push(filters.tags);
    }

    // Realm filtering (search in realm_access JSON)
    if (filters.realmId) {
      conditions.push(`(realm_access->>'boundRealmId' = $${params.length + 1} OR realm_access->'accessibleRealms' ? $${params.length + 1})`);
      params.push(filters.realmId);
    }

    if (conditions.length > 0) {
      query += ` WHERE ${conditions.join(' AND ')}`;
    }

    query += ' ORDER BY created_at DESC';

    const { rows } = await this.db.query(query, params);
    return rows.map(row => this.rowToEntity(row));
  }

  /**
   * Find agents by realm access
   */
  async findByRealmAccess(realmId: string): Promise<Agent[]> {
    const query = `
      SELECT * FROM ${this.getFullTableName()}
      WHERE realm_access->>'boundRealmId' = $1 
         OR realm_access->'accessibleRealms' ? $1
      ORDER BY created_at DESC
    `;
    
    const { rows } = await this.db.query(query, [realmId]);
    return rows.map(row => this.rowToEntity(row));
  }

  /**
   * Update agent's last activity timestamp
   */
  async updateLastActivity(agentId: AgentId): Promise<void> {
    const query = `
      UPDATE ${this.getFullTableName()}
      SET deployment = jsonb_set(deployment, '{lastHeartbeat}', to_jsonb($2::text)),
          updated_at = $2
      WHERE id = $1
    `;
    
    await this.db.query(query, [agentId, new Date().toISOString()]);
  }

  /**
   * Get agents by status
   */
  async findByStatus(status: string): Promise<Agent[]> {
    return this.findAll({ status });
  }

  /**
   * Get agents by type
   */
  async findByType(type: string): Promise<Agent[]> {
    return this.findAll({ type });
  }

  /**
   * Search agents by name pattern
   */
  async searchByName(namePattern: string): Promise<Agent[]> {
    const query = `
      SELECT * FROM ${this.getFullTableName()}
      WHERE name ILIKE $1
      ORDER BY name ASC
    `;
    
    const { rows } = await this.db.query(query, [`%${namePattern}%`]);
    return rows.map(row => this.rowToEntity(row));
  }

  /**
   * Get agent statistics
   */
  async getStatistics(): Promise<{ total: number; byType: Record<string, number>; byStatus: Record<string, number> }> {
    const totalQuery = `SELECT COUNT(*) as count FROM ${this.getFullTableName()}`;
    const typeQuery = `SELECT type, COUNT(*) as count FROM ${this.getFullTableName()} GROUP BY type`;
    const statusQuery = `SELECT status, COUNT(*) as count FROM ${this.getFullTableName()} GROUP BY status`;

    const [totalResult, typeResult, statusResult] = await Promise.all([
      this.db.query(totalQuery),
      this.db.query(typeQuery),
      this.db.query(statusQuery)
    ]);

    const byType: Record<string, number> = {};
    typeResult.rows.forEach(row => {
      byType[row.type] = parseInt(row.count, 10);
    });

    const byStatus: Record<string, number> = {};
    statusResult.rows.forEach(row => {
      byStatus[row.status] = parseInt(row.count, 10);
    });

    return {
      total: parseInt(totalResult.rows[0].count, 10),
      byType,
      byStatus
    };
  }
}